kubesphere/kube-design

yarn.lock
Reverts kubesphere/kube-design#3
=> Revert "build(deps): Bump websocket-extensions from 0.1.3 to 0.1.4"

.storybook/stories/Components/TextArea.stories.mdx, src/components/TextArea/TextArea.jsx, src/components/TextArea/styles.scss, yarn.lock
=> textarea add auto resize

.github/workflows/main.yml, babel.config.js, jest.config.js, jest/setupTests.js, jest/styleMock.js, package.json, src/components/Alert/Alert.test.js, src/components/Button/Button.jsx, src/components/Button/styles.scss, src/components/Form/Form.test.js, webpack.config.js, yarn.lock
=> chore: setup for unit tests and github action

.storybook/stories/Components/Select.stories.mdx, src/components/Checkbox/Checkbox.jsx, src/components/Select/Option.jsx, src/components/Select/Select.jsx, src/components/Select/elementPos.js, src/components/Select/index.js, src/components/Select/styles.scss, src/styles/variables.scss, src/utils/index.js
=> add: Add the base select component

src/components/Alert/Alert.jsx, src/components/Button/Button.jsx, src/components/Checkbox/Checkbox.jsx, src/components/Collapse/Collapse.jsx, src/components/Dropdown/Dropdown.jsx, src/components/Form/Form.jsx, src/components/Icon/index.js, src/components/Input/Input.jsx, src/components/Loading/Loading.jsx, src/components/Menu/Menu.jsx, src/components/Notify/Notify.jsx, src/components/Pagination/Pagination.jsx, src/components/Popper/Popper.jsx, src/components/Progress/Progress.jsx, src/components/Radio/Radio.jsx, src/components/Select/Option.jsx, src/components/Select/Select.jsx, src/components/Select/styles.scss, src/components/Slider/Slider.jsx, src/components/Table/Table.jsx, src/components/Tag/Tag.jsx, src/components/TextArea/TextArea.jsx, src/components/Toggle/Toggle.jsx, src/components/Tooltip/Tooltip.jsx, src/styles/all.scss
=> fix: Fix styles build and import

.github/workflows/release.yml, package.json, yarn.lock
=> chore: Update github action

.github/workflows/main.yml, package.json, yarn.lock
Reverts kubesphere/kube-design#21
=> Revert "chore: Update github action"

.npmignore, README.md, package.json, src/components/Layout/styles.scss, src/styles/main.scss
=> fix: Fix bulma scss import

src/components/Alert/Alert.jsx
=> fix: Fix alert component styles

.github/workflows/release.yml, package.json
=> chore: Add semantic release script

src/components/Collapse/styles.scss, src/components/Toggle/Toggle.jsx, src/components/Toggle/styles.scss
=> fix: Remove default toggle text

src/components/Form/Form.jsx, src/components/Form/Item.jsx
=> update: Add Form onChange event

src/components/Form/Item.jsx, src/components/Select/Select.jsx, src/components/Select/styles.scss
=> fix: Fix some styles in Select

src/components/AutoComplete/AutoComplete.jsx
See https://github.com/krisk/Fuse/issues/495
=> fix: Fix fuse.js compatible error

.storybook/stories/Components/DatePicker.stories.mdx, src/components/AutoComplete/AutoComplete.jsx, src/components/DatePicker/DatePicker.jsx, src/components/DatePicker/flatpickr.scss, src/components/DatePicker/styles.scss, src/components/LocaleProvider/LocaleProvider.jsx, src/styles/main.scss
=> fix: Fix DatePicker styles error

src/components/Button/Button.jsx, src/components/Button/styles.scss, src/components/Pagination/Pagination.jsx, src/components/Pagination/styles.scss, src/components/Table/styles.scss
=> fix: Fix pagination and button styles

src/components/Slider/Slider.jsx
=> fix: Update slider rect value when mouse down

.storybook/stories/Components/Checkbox.stories.mdx, src/components/Checkbox/CheckboxGroup.jsx, src/components/Slider/Slider.jsx
=> fix: Fix checkbox group children not render

src/components/Select/Select.jsx
=> fix: Fix multi select with search

src/components/Pagination/Pagination.jsx
=> fix: Fix pagination totalPage error

src/components/Collapse/Collapse.jsx, src/components/Collapse/CollapseItem.jsx
=> fix: Fix collapse component visible logic

src/components/Table/Table.jsx
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>
What type of PR is this?
/kind bug
What this PR does / why we need it:
Which issue(s) this PR fixes:
Fixes #45 
/assign @leoendless
=> fix: Fix the Table column are changed but it does not render

.storybook/stories/Components/Table.stories.mdx, src/components/Form/Item.jsx, src/components/Input/InputSearch.jsx, src/components/Table/Tbody.jsx, src/components/Table/Tr.jsx
=> fix: Fix tr checkbox props in table

src/components/Loading/LoadingIcon.jsx, src/components/Loading/styles.scss
Signed-off-by: TheYoungManLi <1512298456@qq.com>
/assign @leoendless
=> fix: use css3 animation property for loading

src/components/Input/InputSearch.jsx
=> fix: Fix input search value state

src/components/Checkbox/Checkbox.jsx
=> fix: Fix controlled checkbox update logic

src/components/Pagination/Pagination.jsx
=> fix: Fix pagination total page

src/components/Layout/styles.scss, src/styles/main.scss
=> fix: Fix variables scss import error

.storybook/stories/Components/Form.stories.mdx, src/components/Form/Group.jsx, src/components/Form/styles.scss
=> fix: Fix form group keepDataWhenUnCheck style

src/components/Select/Select.jsx
Signed-off-by: lannyfu <lannyfu@yunify.com>
to Fixed #[#kubesphere/kubesphere/3483](https://github.com/kubesphere/kubesphere/issues/3483)
=> fix: Add conditions of changing state on Select

src/components/Input/Input.jsx
Signed-off-by: xuliwenwenwen <liwenxu@yunify.com>
/kind bug
Fixes #[#kubesphere/console#2131](https://github.com/kubesphere/console/issues/2131)
=> fix: Fix input password value attribute from dom

src/components/Select/Select.jsx
Signed-off-by: xuliwenwenwen <liwenxu@yunify.com>
=> feat: Support select custom dropdown content

src/components/Select/Select.jsx
Signed-off-by: xuliwen <xuliwen@xuliwendeMacBook-Pro-2.local>
=> feat: add delete trigger update of the multi select

src/components/Table/Tbody.jsx, src/components/Table/Tr.jsx, src/components/Table/styles.scss
Signed-off-by: xuliwenwenwen <liwenxu@yunify.com>
=> fix: expand table style

src/components/Input/Input.jsx
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>
=> fix: Remove the value attribute of the input that the type is the password

src/components/Table/Table.jsx, src/components/Table/Td.jsx
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>
=> Fix: Fixed table not refreshing when column changed

src/components/Tag/Tag.jsx, src/components/Tag/styles.scss
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>
=> Fix: Add critical type in Tag

src/components/Input/Input.jsx
Signed-off-by: harrisonliu5 <harrisonliu@kubesphere.io>
=> fix: Fix the password input is no value

src/components/Icon/spirits.js
=> feat: Add node group icon

.changeset/clever-clocks-wave.md, packages/components/src/FilterInput/FilterInput.tsx
https://github.com/kubesphere/issues/issues/1381
https://github.com/kubesphere/issues/issues/1370
=> fix: resolved FilterInput bugs

packages/components/src/DatePicker/locales/en.ts
Fix English translation of DatePicker
=> fix:  English translation of DatePicker

.changeset/clever-clocks-wave.md
=> docs: changeset

packages/components/src/TypeSelect/TypeSelect.story.tsx, packages/components/src/TypeSelect/TypeSelect.styles.ts, packages/components/src/TypeSelect/TypeSelect.tsx
fixed: https://github.com/kubesphere/gd-issues/issues/1
=> feat: TypeSelect add searchable props

.storybook/stories/Components/Select.stories.mdx, src/components/Select/Select.jsx
fixed #https://github.com/kubesphere/issues/issues/3175
=> fix: Fix compatibility issues with select on Windows.

.changeset/polite-shoes-kick.md, .changeset/proud-crabs-sniff.md, .changeset/rich-kings-wave.md
Signed-off-by: donniean <donniean1@gmail.com>
=> docs: add hooks docs

.storybook/stories/Components/Select.stories.mdx, src/components/Select/Option.jsx, src/components/Select/Select.jsx, src/components/Select/styles.scss
Select add showTip support MultiValue ValueRenderer And OptionRender
=> fix: Select add showTip support MultiValue ValueRenderer And OptionRender

.github/workflows/npm.deprecate.yml
Signed-off-by: donniean <donniean1@gmail.com>
=> ci: add .github/workflows/npm.deprecate.yml

.github/workflows/npm.deprecate.yml
Signed-off-by: donniean <donniean1@gmail.com>
=> ci: add new

.changeset/itchy-feet-cry.md
https://github.com/kubesphere/kube-design/pull/275
=> chore: Update version

.changeset/tender-actors-notice.md, packages/components/src/Sheet/Sheet.styles.ts, packages/components/src/Sheet/Sheets.tsx, packages/components/src/Table/BaseTable/TableCell.tsx, packages/components/src/Table/BaseTable/TableRow.tsx, packages/components/src/Table/BaseTable/Toolbar/index.tsx, packages/components/src/Table/DataTable/Table.tsx, packages/components/src/Table/DataTable/TableHead.tsx, packages/components/src/Table/DataTable/Toolbar.tsx, packages/components/src/Table/DataTable/utils/index.tsx
1. fix: Add enableSorting in getDefaultTableOptions function
2. fix: Fix sheet content title
3. style: Fix table styles
=> fix: Fix bugs

README.md
=> chore: update README doc link

.gitignore, src/components/Select/Select.jsx
link #https://github.com/kubesphere/project/issues/6903
=> fix: adjust scroll threshold for fetching more items in Select component
